import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {

  const [numberOfRequests, setNumberOfRequests] = useState("0");
  const [walletConnected, setWalletConnected] = useState("false");

  const connectWallet = async () => {
    try{
      await getProviderOrSigner();
      setWalletConnected(true);
    }catch(error){
      console.error(error);
    }
  }

  const getProviderOrSigner = async(signer = false) => {

  }

  function renderRequest(){
    return(
      <div></div>
    )
  }

  function renderDonate(){
    return(
      <div>

      </div>
    )
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main} class="bg-pink-50">
        <nav class="px-4 py-3 bg-black text-white flex justify-end fixed w-full top-0">
          <ul class="pl-28 py-1 flex space-x-11">
              <li class="cursor-pointer" onClick={renderRequest()}>Request</li>
              <li class="cursor-pointer">Donate</li>
              <li class="cursor-pointer">Vote</li>
              <button class="bg-purple-400 rounded-lg text-white px-4 py-1 font-semibold" onClick={connectWallet}>Connect Wallet</button>
          </ul>
        </nav>
        <div class=" bg-purple-500">
        <div>
            <p class="text-center p-8 text-teal-600 text-6xl font-bold">Request Form</p>
        </div>
        <div class="mx-80 my-10 px-20 py-10 border-solid border-8 border-blue-800 rounded-2xl space-y-2">
            <p class="text-2xl font-semibold">Hospital/Organisation Name:</p>
            <input type="text" class="border-solid border-[3px] border-rose-600 w-full"/>
            
            <div class="flex space-x-10 pt-5">
                <p class="text-2xl font-semibold">City:</p>
                <input type="text" class="border-solid border-[3px] border-rose-600 w-1/3 h-8"/>
                <p class="text-2xl font-semibold">Country:</p>
                <input type="text" class="border-solid border-[3px] border-rose-600 w-1/3"/>
            </div>
            <div class="flex space-x-10 pt-5">
                <p class="text-2xl font-semibold whitespace-nowrap">Email ID:</p>
                <input type="text" class="border-solid border-[3px] border-rose-600 w-full"/>
            </div>
            <div class="flex space-x-10 pt-5">
                <p class="text-2xl font-semibold whitespace-nowrap">Amount (in Ether):</p>
                <input type="number" class="border-solid border-[3px] border-rose-600 w-full"/>
            </div>
            <p class="text-2xl font-semibold pt-5">Description:</p>
            <textarea type="text" class="border-solid border-[3px] border-rose-600 w-full h-36" cols="100"></textarea>
            <div class="text-center pt-5">
                <button type="submit" class="bg-rose-600 text-white p-4 text-xl rounded-2xl">SUBMIT</button>
            </div>
        </div>
    </div>
      </main>

      <footer className={styles.footer}>
        <p>Made by Varun & Tushar</p>
      </footer>
    </div>
  )
}
